// Wygląd maila: branding (kolory, logo, stopka) i klocki HTML.
// Plik zależny od projektu - przy kopiowaniu workera zmieniasz BRAND i ewentualnie teksty.
// Tylko tabele i style inline (klienci poczty, w tym Outlook).
// Wzór: szablony `admin` w reference/form-config-*.json.

import { html, multiline, type SafeHtml } from './html.ts'

export const BRAND = {
  companyName: 'BramBruk',
  tagline: 'Ogrodzenia • Brukarstwo • Budownictwo',
  siteName: 'brambruk.pl',
  siteUrl: 'https://brambruk.pl',
  /** Gdy brak zmiennej LOGO_URL. */
  defaultLogoUrl: 'https://brambruk.pl/assets/logo/znak-144.png',
  colors: {
    page: '#e8e8e8',
    topBar: '#98af15',
    heading: '#5a5343',
    accent: '#b5cc1c',
    link: '#89a66f',
    card: '#f8f9f7',
    footer: '#5a5343',
    button: '#98af15',
    text: '#2c2c2c',
    muted: '#5a5a5a',
    note: '#8a8580',
    border: '#ececec',
  },
} as const

/** Teksty stałe maila (poza danymi formularza). Bez pauz (—), tylko łącznik (-). */
export const TEXT = {
  sitePrefix: 'Na stronie',
  autoGenerated: 'Ta wiadomość została wygenerowana automatycznie.',
  goToSite: 'Przejdź na stronę',
  meta: (formName: string, requestId: string) => `Formularz: ${formName} · ID zgłoszenia: ${requestId}`,
}

const c = BRAND.colors
const FONT = 'font-family:Arial,Helvetica,sans-serif;'

export interface LayoutInput {
  subject: string
  heading: string
  intro: string
  formName: string
  requestId: string
  logoUrl: string
  sections: SafeHtml[]
}

export function layoutHtml(input: LayoutInput): string {
  return html`<!DOCTYPE html>
<html lang="pl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light">
<title>${input.subject}</title>
</head>
<body style="margin:0;padding:0;background:${c.page};">
<div style="display:none;font-size:1px;line-height:1px;max-height:0;max-width:0;opacity:0;overflow:hidden;mso-hide:all;">${input.subject}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:0;padding:0;border-collapse:collapse;background:${c.page};">
<tr><td align="center" style="padding:28px 12px;">
<table role="presentation" width="640" cellpadding="0" cellspacing="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border:1px solid ${c.border};border-radius:16px;overflow:hidden;border-collapse:separate;">
<tr><td style="background:${c.topBar};padding:14px 18px;${FONT}">
<div style="font-size:15px;line-height:20px;color:#ffffff;font-weight:700;letter-spacing:0.2px;">${input.heading}</div>
</td></tr>
<tr><td style="padding:22px 22px 14px;${FONT}">
<div style="font-size:24px;line-height:30px;color:${c.heading};font-weight:800;">${input.heading}</div>
<div style="height:8px;line-height:8px;font-size:1px;">&nbsp;</div>
<div style="font-size:15px;line-height:22px;color:${c.muted};">${TEXT.sitePrefix} <a href="${BRAND.siteUrl}" style="color:${c.link};text-decoration:underline;">${BRAND.siteName}</a> ${input.intro}</div>
</td></tr>
${input.sections}
${footer(input)}
</table>
</td></tr>
</table>
</body>
</html>`.value
}

function footer(input: LayoutInput): SafeHtml {
  return html`<tr><td style="background:${c.footer};padding:18px 22px;${FONT}">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="border-collapse:collapse;">
<tr>
<td align="left" style="vertical-align:middle;padding-right:10px;width:74px;"><a href="${BRAND.siteUrl}" style="text-decoration:none;border:0;display:inline-block;"><img src="${input.logoUrl}" width="64" alt="${BRAND.companyName}" style="display:block;border:0;outline:none;height:auto;max-width:64px;"></a></td>
<td style="vertical-align:middle;${FONT}">
<div style="font-size:18px;line-height:24px;color:#ffffff;font-weight:800;">${BRAND.companyName}</div>
<div style="font-size:13px;line-height:18px;color:#ffffff;opacity:0.92;">${BRAND.tagline}</div>
</td>
<td align="right" style="vertical-align:middle;"><a href="${BRAND.siteUrl}" style="display:inline-block;background:${c.button};color:#ffffff;text-decoration:none;${FONT}font-size:14px;font-weight:700;line-height:18px;padding:10px 16px;border-radius:10px;">${TEXT.goToSite}</a></td>
</tr>
</table>
<div style="height:12px;line-height:12px;font-size:1px;">&nbsp;</div>
<div style="font-size:12px;line-height:18px;color:#ececec;">${TEXT.autoGenerated}</div>
<div style="font-size:12px;line-height:18px;color:#ececec;">${TEXT.meta(input.formName, input.requestId)}</div>
</td></tr>`
}

/** Karta sekcji (tło, zaokrąglenie, tytuł, opcjonalny dopisek). */
export function sectionCard(title: string, content: SafeHtml[], note?: string): SafeHtml {
  return html`<tr><td style="padding:0 22px 14px 22px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:${c.card};border:1px solid ${c.border};border-radius:14px;">
<tr><td style="padding:16px;${FONT}">
<div style="font-size:17px;line-height:24px;color:${c.text};font-weight:800;margin:0 0 12px;">${title}</div>
${content}
${note ? html`<div style="font-size:12px;line-height:18px;color:${c.note};margin-top:8px;">${note}</div>` : ''}
</td></tr>
</table>
</td></tr>`
}

export interface Row {
  label: string
  value: string
  /** Adres e-mail - wartość jako link mailto:. */
  mailto?: boolean
}

/** Pola krótkie: wiersze "etykieta: wartość". */
export function rowsTable(rows: Row[]): SafeHtml {
  return html`<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="${FONT}font-size:14px;line-height:20px;">
${rows.map(
  (row) => html`<tr><td style="color:${c.muted};width:150px;padding:5px 0;vertical-align:top;">${row.label}:</td><td style="color:${c.text};padding:5px 4px;word-break:break-word;overflow-wrap:anywhere;">${
    row.mailto
      ? html`<a href="${mailtoHref(row.value)}" style="color:${c.link};text-decoration:underline;">${row.value}</a>`
      : html`<strong>${multiline(row.value)}</strong>`
  }</td></tr>
`,
)}</table>`
}

/** Pole textarea: osobny blok z akcentem lewej krawędzi. */
export function textBlock(text: string, label?: string): SafeHtml {
  return html`${label ? html`<div style="font-size:13px;line-height:18px;color:${c.muted};margin:8px 0 6px;">${label}:</div>` : ''}<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#ffffff;border:1px solid ${c.border};border-left:6px solid ${c.accent};border-radius:12px;">
<tr><td style="padding:14px;${FONT}font-size:14px;line-height:22px;color:${c.text};word-break:break-word;overflow-wrap:anywhere;">${multiline(text)}</td></tr>
</table>`
}

/**
 * mailto: z zakodowanymi znakami specjalnymi (?, &, # itd.), żeby adres
 * z formularza nie dopisał tematu czy odbiorców do odpowiedzi.
 */
function mailtoHref(email: string): string {
  return 'mailto:' + email.replace(/[^A-Za-z0-9.@_+-]/gu, (char) => encodeURIComponent(char))
}

/** Wersja tekstowa: ten sam układ bez HTML. */
export function layoutText(input: Omit<LayoutInput, 'sections' | 'logoUrl'> & { sections: string[] }): string {
  return [
    input.heading,
    `${TEXT.sitePrefix} ${BRAND.siteName} ${input.intro}`,
    '',
    input.sections.join('\n\n'),
    '',
    '-- ',
    TEXT.autoGenerated,
    TEXT.meta(input.formName, input.requestId),
    '',
  ].join('\n')
}
